---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
- target:
    kind: ConsoleLink
    name: tower
  patch: |-
    - op: replace
      path: /spec/href
      value: 'https://tower-ansible-automation-platform.apps.hub-adetalhouet.rhtelco.io'
